services:
  - type: web
    name: fleet-manager
    runtime: node
    repo: https://github.com/ces0491/fleet-manager
    region: oregon
    plan: free
    buildCommand: cd backend && npm ci && npm run build && cd ../frontend && npm ci && npm run build
    startCommand: cd backend && npm run prisma:migrate && node dist/server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: fleet-db
          property: connectionString

databases:
  - name: fleet-db
    plan: free
    region: oregon
